### ISSUE TITLE
Support multiple values for githubOrg

### ISSUE THREAD

**Issue by nexdrew** [npm/npme-auth-github#38]
For the benefit of npm Enterprise, it should probably accept both an array and a string value that can be parsed into multiple values.

**Comment by nanovazquez** [comment]
Any news on this? I'm not aware of all the changes needed in npm enterprise to support this, but to implement it here we can simply query all the orgs until the user is authenticated in one of them, like (credits to @xaka).

**authenticator.js** ([line 84](https://github.com/mulesoft-labs/npme-auth-github/blob/4251dd539b74d3de57bcadb6fa6e406c2609546b/authenticator.js#L84))
```javascript
  }).then(_this.githubOrg && function(token) {
    return Promise.any([].concat(_this.githubOrg).map(function (githubOrg) {
      return new Promise(function(resolve, reject) {
        github.orgs.getMember({ user: username, org: githubOrg }, function(err, res) {
          if (err) reject(err);
          else resolve(token);
        });
      });
    })).catch(function(err) {
      // handle possible AggregateError, which is a collection of promise errors
      err = err instanceof Promise.AggregateError ? err[0] : err;

      if (err.code === 404) {
        err.code = 401;
        err.message = 'unauthorized';
      } else if (err.code === 500) {
        err.message = 'GitHub enterprise unavailable';
      }

      // this is an error state
      throw err;
    });
  });
};
```

To support either an `array` and a `string` value, you can do the following (tests [here](http://jsbin.com/noxukobufa/edit?js,console)):

```
var items = !Array.isArray(_this.githubOrg) ? _this.githubOrg.split(/,[\s]*/) : value;
```

But I'm not sure if this is the right place to do it. If so, the line should be added above the `return Promise.any([].concat(...`. 

Also, I'd like to know if there's a way to test this code locally / setup steps run the tests, as my current tests failed because Redis is not present locally:

```
➜  npme-auth-github git:(master) ✗ npm run test

> @npm/npme-auth-github@1.4.0 test /Users/marianovazquez/projects/npme-auth-github
> lab -v -c --timeout 1000 test/ --ignore '$$bole'

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
```

**Comment by bcoe** [comment]
@nanovazquez in my QA; #39 doesn't seem to quite do the trick, because at publish time it gets an invalid org error, caused by: https://github.com/npm/npme-auth-github/blob/master/authorizer.js#L83

I think it should be a pretty quick fix; if you get to it before me I can land the feature ASAP.

**Comment by nanovazquez** [comment]
@bcoe: there you go #40 

I'm using the same approach the ** authenticator.js** uses: `this.githubOrg` could be an Array, a CSV or a single value. We simply check if the parameter received is one of the orgs defined via configuration.

**Comment by bcoe** [comment]
@nanovazquez I just released a new version of npm Enterprise with support for multiple organizations (via your patch); please let me know if this does the trick for you.

**Comment by nanovazquez** [comment]
@bcoe: Does this update contains the fix? This is the latest version I see in the website.

![image](https://cloud.githubusercontent.com/assets/1306634/24099966/b472cb8a-0d50-11e7-9ab1-ef3228300059.png)

**Comment by bcoe** [comment]
@nanovazquez yes! let me know if you run into any issues.

**Comment by nanovazquez** [comment]
Worked! Thanks :)

**Comment by nanovazquez** [comment]
@bcoe: Worked! Thanks for taking care of this :)
